baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Eldiron'

theme = "hello-friend-ng"
paginate = 5

enableSharingButtons = true

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # "light" or "dark"
  defaultTheme = "dark"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3

  # Show reading time in minutes for posts
  showReadingTime = false

  # Show table of contents at the top of your posts (defaults to false)
  # Alternatively, add this param to post front matter for specific posts
  toc = true

  # Show full page content in RSS feed items
  #(default is Description or Summary metadata in the front matter)
  # rssFullText = true

  homeSubtitle = "Create Your Own RPGs"

  #enableThemeToggle = true

  [[params.social]]
  name = "github"
  url = "https://github.com/markusmoenig/Eldiron"

  [[params.social]]
  name = "twitter"
  url = "https://twitter.com/MarkusMoenig"

  [[params.social]]
  name = "patreon"
  url = "https://patreon.com/eldiron"

  [params.portrait]
  path     = "logo.png"

  [params.footer]
  trademark = true
  copyright = true

    [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

[languages]
  [languages.en]
    title = "Eldiron"
    subtitle = ""
    keywords = "rpg, creator, maker, game"
    copyright = "Markus Moenig"
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    # leave empty to disable, enter display text to enable
    # lastModDisplay = ""

    [languages.en.params.logo]
      logoText = "Eldiron"
      logoHomeLink = "/"
      logoCursorColor = "#ffffff"

    [languages.en.menu]

      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"

      [[languages.en.menu.main]]
        identifier = "features"
        name = "Features"
        url = "/features"

      [[languages.en.menu.main]]
        identifier = "book"
        name = "The Book"
        url = "https://book.eldiron.com"